### ISSUE TITLE
wrong registrations numbers shown

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#100]
We have two communities:
* LEU: 42 registered 
* ASL: 10 registered

The map shows LEU in green, but ASL in orange.

expected:
* The summary in the "Registering" block of the explorer shows 42, should show 52
* The ASL community Pin should be shown green as well, as it has 1 meetup assigned (orange might actually be ok, but I'd like to understand why)

The "Assigning" Block correctly shows 6 meetups assigned: 5 Leu + 1ASL
 

![image](https://user-images.githubusercontent.com/10366175/198833982-3de0a58e-4036-42f0-b1e9-96612bc26efd.png)

**Comment by Jay-Forrer** [comment]
![image](https://user-images.githubusercontent.com/55161261/200139041-293d5f4b-222b-49e0-8458-5355604d924a.png)
I found the Problem. The Icon is yellow until there are more than 1 meetup. This was found in the MarkerIcon.js File. Line 45. I could change it to a >=, if you want it

**Comment by brenzi** [comment]
This may have been deliberate, but I'm not sure it makes sense. Let's do the change plz
