### ISSUE TITLE
tentative community growth does not make sense

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#101]
with 42 registered participants and 8 newbies, tentative growth is reported as 0.04%

given 184 reputables, 8 newbies should be 5%

![image](https://user-images.githubusercontent.com/10366175/198888597-ec4816ee-40c7-46d3-8d8e-466522efd506.png)

**Comment by brenzi** [comment]
@clangenb can you remind me why we exclude endorsements here? They count to growth as well. Not sure what the reasoning was

**Comment by clangenb** [comment]
I can't remember either, but I agree now that it does not make sense.

**Comment by brenzi** [comment]
ok then let's do this:
* fix calculation which seems not result in percent
* include endorsees in growth share: `tentative_growth = (newbies + endorsees) / number of unique reputables `
