### ISSUE TITLE
update to notee node (Gesell) v0.4.0

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#40]
update explorer to work with new Gesell encointer/encointer-node v0.4.0:

https://github.com/encointer/encointer-node/releases/tag/v0.4.0

**Comment by brenzi** [comment]
@demyanrogozhin we haven't updated the testnet Gesell yet, want to have a PR ready first.

If there are difficulties to be backwards compatible with Cantillon, don't bother. For the time being, we focus on Gesell and Parachain, we can worry again about Cantillon later

**Comment by brenzi** [comment]
local testing:

start node with
```
  ./target/release/encointer-node-notee --dev --tmp --enable-offchain-indexing true
```
then run this script in `./client`
```
  ./bootstrap_demo_community.py
```

**Comment by anizeani** [comment]
@brenzi, can we close this issue?
