### ISSUE TITLE
Map.js: 356 instead of 365? 

### ISSUE THREAD

**Issue by anizeani** [encointer/explorer#44]
In the Map.js https://github.com/encointer/explorer/blob/master/src/Map.js:
The following line is:
const BLOCKS_PER_MONTH = (86400 / 6) * (356 / 12);
Shouldn't it be 365 for 365 days?

**Comment by clangenb** [comment]
Haha, I don't see why this should be my assignment, but I agreed that it should probably be 365.

**Comment by anizeani** [comment]
this PR #51 should close this task
