### ISSUE TITLE
Display and animate registered participants in registering phase

### ISSUE THREAD

**Issue by clangenb** [encointer/explorer#58]
Currently, the registered participants are fetched via the `assignmentsCounts` storage value. However, this storage value is only available once the `assignmentPhase` starts. 

We'd like to animate regsitrations as they come in as we did berfore (Gesell 0.6.0 and earlier)

1. With encointer/encointer-js#40 we can get the current number of participants even during the REGISTERING phase
2. have the explorer listen to the `ParticipantRegistered` event and animate every single registration during registering phase

**Comment by brenzi** [comment]
I'd like to have the explorer listen to events (pallets#130) and animate every single registration during registering phase

**Comment by clangenb** [comment]
Superseded by #89
