### ISSUE TITLE
show next ceremony date and time in CurrencyInfo

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#88]
use first meetup location to calculate ceremony time.
ensure the time is calculated correctly in all cereomony phases

**Comment by clangenb** [comment]
* get meetup locations: `api.rpc.encointer.getLocations(cid)`

* calculate meetup time with helper in encointer-js: https://github.com/encointer/encointer-js/blob/a25b5087c8e35d76f62395cf8adc4f19cd1c11e6/packages/node-api/src/encointer-api.ts#L172

**Comment by Jay-Forrer** [comment]
I made that you're able to see the time, when the Ceremony starts. The Problem that I was facing, was that I wasn't able to show the Timezone of the respective Community.

**Comment by brenzi** [comment]
Ok. One step at the time

**Comment by Jay-Forrer** [comment]
I think I found a way to get the Timezones from specific lat longs, but it requires that I get a node module called timespace. All the other ways requires that we communicate with an API, which we need a key for and probably costs some money. The License for timespace is a MIT License where it says that permission is granted free of charge. If it's ok for you I'll be using timespace.

**Comment by brenzi** [comment]
Sounds good
