### ISSUE TITLE
show detailed participant registry at all times

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#89]
during registering:
show recent number of bootstrappers, endorsees, reputables, newbies

during assigning and attesting:
* also show how many have not been assigned in red per category

**Comment by clangenb** [comment]
During registering phase query:
* registered bootstrappers: `encointerCeremonies.bootstrapperCount`
* registered reputables: `encointerCeremonies.reputableCount`
* registered endorsees: `encointerCeremonies.endorseeCount`
* registered newbies: `encointerCeremonies.newbieCount`

During assigning and attesting query:
* `encointerCeremonies.assignmentCounts`: then get field: `assignmentCounts.newbies`.
-> unassigned newbies: `enconterCeremonies.newbieCount - assignmentCounts.newbies`

**Comment by brenzi** [comment]
closed by #96 and others
