### ISSUE TITLE
show community logo in CurrencyInfo

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#90]
fetch from public ipfs gateway (not encointer's if possible. any gateways which works without api key is fine)

**Comment by Jay-Forrer** [comment]
Do you per chance know the CID of the Logos? realizing the more I read about ipfs, that I would need to have the CID of them.

**Comment by brenzi** [comment]
The cid's of the logos are stored on chain, in the metadata `assets` field of each community:
![image](https://user-images.githubusercontent.com/10366175/194708536-137113d7-5c7d-4baf-9d1c-2cafb4a5bcb9.png)
